/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './app/**/*.{js,jsx}',
        './components/**/*.{js,jsx}',
        './pages/**/*.{js,jsx}',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#f8f9fa',
                    100: '#e9ecef',
                    200: '#d1d5db',
                    300: '#b0b8c4',
                    400: '#9ca3af',
                    500: '#c0c7d0',
                    600: '#a8b0bb',
                    700: '#8a929d',
                    800: '#6b7280',
                    900: '#4b5563',
                    950: '#374151',
                },
                dark: {
                    50: '#f0f1f3',
                    100: '#d4d7dc',
                    200: '#b8bcc4',
                    300: '#8e939e',
                    400: '#5a5f6d',
                    500: '#2e3240',
                    600: '#1e2130',
                    700: '#161923',
                    800: '#0e1018',
                    900: '#09090f',
                    950: '#040407',
                },
                silver: {
                    50: '#fafbfc',
                    100: '#f0f2f5',
                    200: '#e4e7eb',
                    300: '#cdd2d9',
                    400: '#adb4bf',
                    500: '#8e96a3',
                    600: '#6e7787',
                    700: '#515b6b',
                    800: '#3a4250',
                    900: '#262c37',
                },
                accent: {
                    50: '#f2f3f5',
                    100: '#e8eaee',
                    200: '#d4d8df',
                    300: '#bfc5cf',
                    400: '#a3aab8',
                    500: '#c8cdd5',
                    600: '#b0b6c1',
                    700: '#8a919e',
                    800: '#646c7a',
                    900: '#3e4553',
                },
                discord: {
                    blurple: '#5865F2',
                    green: '#57F287',
                    yellow: '#FEE75C',
                    fuchsia: '#EB459E',
                    red: '#ED4245',
                },
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                display: ['Outfit', 'system-ui', 'sans-serif'],
            },
            animation: {
                'slide-in': 'slideIn 0.3s ease-out',
                'fade-in': 'fadeIn 0.3s ease-out',
                'bounce-in': 'bounceIn 0.5s ease-out',
                'pulse-slow': 'pulse 3s ease-in-out infinite',
                'glow': 'glow 2s ease-in-out infinite alternate',
                'shimmer': 'shimmer 2s linear infinite',
            },
            keyframes: {
                slideIn: {
                    '0%': { transform: 'translateX(-100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                bounceIn: {
                    '0%': { transform: 'scale(0.3)', opacity: '0' },
                    '50%': { transform: 'scale(1.05)' },
                    '70%': { transform: 'scale(0.9)' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                glow: {
                    '0%': { boxShadow: '0 0 5px rgba(200, 205, 213, 0.3)' },
                    '100%': { boxShadow: '0 0 20px rgba(200, 205, 213, 0.5)' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'shimmer': 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.05) 50%, transparent 100%)',
            },
        },
    },
    plugins: [],
};
